suyoj-hand-knit-craft/SuyojHandKnitCraft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
]

suyoj-hand-knit-craft/invoice/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('create', views.create_invoice, name='create_invoice'),
    path('delete/<int:id>', views.delete_invoice, name='delete_invoice'),
    path('add-product-to-invoice/<int:id>', views.add_product_to_invoice, name='add_product_to_invoice'),
    path('add-product-to-invoice/ajax/product_price', views.ajax_product_price, name='ajax_product_price'),
    path('add-product-to-invoice/ajax/quantity', views.ajax_product_quantity, name='ajax_product_quantity'),
    path('save', views.save_invoice, name='save_invoice'),
]

suyoj-hand-knit-craft/pages/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('product/', include('products.urls')),
    path('invoice/', include('invoice.urls')),
    path('sales/', include('sales.urls')),

]

suyoj-hand-knit-craft/invoice/models.py
from django.db import models
from datetime import datetime
from products.models import Product
# Create your models here.


class InvoiceId(models.Model):
    date_time = models.DateTimeField(default = datetime.now)

    def __str__(self):
        return str(self.id)


class InvoiceRow(models.Model):
    product_name = models.ForeignKey(Product, on_delete = models.CASCADE)
    invoice_id = models.ForeignKey(InvoiceId, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return str(self.product_name)

suyoj-hand-knit-craft/invoice/forms.py
from django import forms
from .models import InvoiceRow


class InvoiceCreateForm(forms.ModelForm):
    price = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    total = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    quantity = forms.CharField(widget=forms.TextInput(attrs={'type': 'number', 'min': '1'}))

    class Meta:
        model = InvoiceRow
        fields = [
            'invoice_id',
            'product_name',
            'price',
            'quantity',
            'total',
        ]

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if len(price) > 5:
            raise forms.ValidationError("Please enter valid price !!")
        else:
            return price

suyoj-hand-knit-craft/invoice/views.py
from django.shortcuts import render, redirect
from .models import InvoiceId, InvoiceRow, Product
from sales.models import Sales
from .forms import InvoiceCreateForm
from django.http import JsonResponse
from django.db.models import Sum
# Create your views here.


def create_invoice(request):
    if request.method == "POST":
        create_invoice_id = InvoiceId.objects.create()
    last_invoice = InvoiceId.objects.all().last()
    invoice_row = InvoiceRow.objects.filter(invoice_id=last_invoice.id)
    total = InvoiceRow.objects.filter(invoice_id=last_invoice.id).aggregate(Sum('total'))
    return render(request, 'invoice/create_invoice.html', {'invoice_id': last_invoice, 'invoice_row': invoice_row, 'total': total})


def delete_invoice(request, id):
    invoice_row = InvoiceRow.objects.filter(invoice_id=id)
    if invoice_row.exists():
        invoice_id = InvoiceId.objects.get(id=id)
        invoice_id.delete()
        invoice_row.delete()
        return redirect('/')
    else:
        invoice_id = InvoiceId.objects.get(id=id)
        invoice_id.delete()
        return redirect('/')


def add_product_to_invoice(request, id):
    form = InvoiceCreateForm(request.POST or None, initial={'invoice_id': id})
    if request.method == "POST":
        if form.is_valid():
            print("Inside")
            form.save()
            return redirect('/invoice/create')
    return render(request, 'invoice/add_product_to_invoice.html', {'form': form, 'invoice_id': id})


def ajax_product_price(request):
    print(request.method)
    product_id = request.GET.get('product_id', None)
    print(product_id)
    p = Product.objects.get(id=product_id)
    data = {
        'price': p.price
    }
    return JsonResponse(data)


def ajax_product_quantity(request):
    product_id = request.GET.get('product_id', None)
    p = Product.objects.get(id=product_id)
    print(p)
    data = {
        'quantity_left': p.quantity,

    }
    return JsonResponse(data)


def save_invoice(request):
    customer_name = request.POST.get('customer_name', None)
    gender = request.POST.get('gender', None)
    invoice_id = request.POST.get('invoice_id', None)
    total = request.POST.get('total', None)
    invoice = InvoiceId.objects.get(id=invoice_id)
    individual_sale = Sales(customer_name=customer_name, gender=gender, invoice_id=invoice,total=total)
    individual_sale.save()
    return redirect('/')

suyoj-hand-knit-craft/templates/invoice/add_product_to_invoice.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
    <div class="jumbotron">
        <div>
            <h1 align="center">Add Product to Invoice</h1>
<form method="post" id="form1">
     {% csrf_token %}
    {{ form|crispy }}
    <a href="{% url 'create_invoice' %}" class="btn btn-info ml-2 float-left" onclick="return myFunction3()">Back</a>
    <button class="btn btn-info ml-2 float-right" type="submit">Add Product</button>
</form>
        </div>
    </div>
    </div>


{% endblock body %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$("#id_product_name").change(function() {
    let product_id = $(this).val();
    console.log(product_id);

 $.ajax({
        url: 'ajax/product_price',
        data: {
            'product_id': product_id,
        },
        dataType: 'json',
        success: function(data) {
            $("#id_price").val(data.price)

            // alert("A user with this username already exists." + data.price);

        }
    });
    });

$("#id_quantity").keyup(function () {
    let quantity = $(this).val();
    let price = $('#id_price').val();

    $('#id_total').val(quantity*price);

})

function myFunction3(){
	let a = confirm("Are you sure you want to go back?");
    if (a == true) {
        return true
    } else {
        return false
    }
}

$("#id_quantity").keyup(function() {
    let quantity = $('#id_quantity').val();
    let product_id = $('#id_product_name').val();
    $.ajax({
        url: 'ajax/quantity',
        data: {

            'product_id': product_id,
        },
        dataType: 'json',
        success: function(data) {
            let a = data.quantity_left
            if (quantity > data.quantity_left) {
                Swal.fire({
                type: 'error',
                title: "We have only " + a + " quantity left !! ",
                showConfirmButton: false,
                timer: 1500,
            }).then(function(){
                   clearInputs();
            });
                //alert("We have only " + data.quantity_left + " quantity left !!");

            }
        }
    });
});

function clearInputs() {
    document.getElementById("id_quantity").value = "";
    document.getElementById("id_total").value = "";

}

document.querySelector('#form1').addEventListener('submit', function(e) {
	let form = this;
    e.preventDefault();
    Swal.fire({
        type: 'success',
        title: 'Successfully Added Product !!',
        showConfirmButton: false,
        timer: 1500,
    }).then(function(){
         form.submit();
    });



});
</script>
{% endblock js %}

suyoj-hand-knit-craft/templates/invoice/create_invoice.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="jumbotron">
        <div>
            <h1 align="center"><< INVOICE -No : {{invoice_id}} >> </h1>

        </div>
        <br>
        <br>
        <div>
            <a href="{% url 'add_product_to_invoice' invoice_id  %}" class="btn btn-info ml-2 float-right">Select Product</a>
            <form method="post" action="{% url 'delete_invoice' invoice_id %}" >
                {% csrf_token %}
                <button class="btn btn-primary ml-2 float-right" onclick="return myFunction3()">Back</button>
            </form>
            <form method="post" action="{% url 'save_invoice' %}" id="form1">
                {% csrf_token %}
                <input type="hidden" name="invoice_id" value="{{ invoice_id }}"/>
                <input type="hidden" name="total" value="{{ total.total__sum }}"/>
                Customer Name : <input type="text" name="customer_name" required/>
                <br>
                <br>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        Gender : <input type="radio" class="form-check-input" name="gender" checked="checked" value="M">Male
                    </label>
                </div>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="gender" value="F">Female
                    </label>
                    <button class="btn btn-primary ml-2 float-right" type="submit">Create Bill</button>
                    </div>
            </form>
        </div>

        </div>
  <table id="myTable" class="table table-bordered">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% if invoice_row %}
                {% for t in invoice_row %}
                <tr>
                    <td>{{ t.product_name }}</td>
                    <td>{{ t.price }}</td>
                    <td>{{ t.quantity }}</td>
                    <td>{{ t.total }}</td>
                </tr>
                {% endfor %}
                {% endif %}
                <tr>
                    <td>__</td>
                    <td>__</td>
                    <td>Grand Total</td>
                    <td>{{total.total__sum}}</td>
                </tr>
            </tbody>
        </table>
    </div>
        {% endblock %}

{% block js %}
    <script>
function myFunction3() {
    let a = confirm("Are you sure you want to go back?");
    if (a == true) {
        return true
    } else {
        return false
    }
}

document.querySelector('#form1').addEventListener('submit', function(e) {
	let form = this;
    e.preventDefault();
    Swal.fire({
        type: 'success',
        title: 'Successfully Created Bill !!',
        showConfirmButton: false,
        timer: 1500,
    }).then(function(){
         form.submit();
    });



});
</script>
{% endblock js %}